default: &default
  adapter: postgresql
  encoding: unicode
  username: mikkie
  password: 12345678
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: img_development

production:
  <<: *default
  database: img_production

test:
  <<: *default
  database: img_test